name: Trigger Unowned Repository Scan

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      dry-run:
        description: Whether to dry-run archival
        required: true
        default: "true"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  trigger:
    name: Trigger Unowned Repository Scan
    runs-on: [self-hosted, universal]
    steps:
      - name: Send repository_dispatch event to GitHub
        uses: actions/github-script@v6
        with:
          script: |
            const [owner, repository] = '${{ github.repository }}'.split("/")
            if (!owner || !repository) {
              core.error('No owner or repository was found in the runner context - exiting.')
              process.exit(1)
            }

            const endpoint = `/repos/${owner}/${repository}/dispatches`
            core.info(`Dispatching 'repository_dispatch' event to '${endpoint}'`)

            const dryRunInput = ${{ github.event.inputs.dry-run }}

            const response = await octokit.request(`POST ${endpoint}`, {
              owner: owner,
              repo: repository,
              event_type: 'trigger-archival',
              client_payload: {
                'dry-run': dryRunInput !== 'false'
              }
            })

            core.info(response)
