name: Send default branch name to OpsLevel

on:
  schedule:
    - cron: "0 9,12,16 * * *"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  trigger-opslevel-default-branch-name-check:
    name: Trigger Opslevel default branch name check
    runs-on: ubuntu-latest
    steps:
      - name: Trigger check
        id: opslevel-default-branch-name-check
        uses: pleo-io/opslevel-default-branch-check@main
        with:
          opsLevelApiToken: ${{ secrets.OPSLEVEL_API_TOKEN }}
          opsLevelCustomEventSecret: ${{ secrets.OPSLEVEL_CUSTOM_EVENT_SECRET }}
          defaultBranch: main
