name: Trigger Unowned Repository Scan

on:
  schedule:
    - cron: "0 9 * * 1-5"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
  
env:
  dry_run: false

jobs:
  trigger:
    name: Trigger Unowned Repository Scan
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: trigger-archival
          client-payload: '{ "dry-run": ${{ env.dry_run }} }'
