name: Trigger Unowned Repository Scan

on:
  schedule:
    - cron: "0 9 * * 1-5"
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  trigger:
    name: Trigger Unowned Repository Scan
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch event
        uses: peter-evans/repository-dispatch@v2
        env:
          SHOULD_DRY_RUN: ${{ secrets.SHOULD_DRY_RUN || true }}
        with:
          event-type: trigger-archival-test
          client-payload: '{ "dry-run": ${{ env.SHOULD_DRY_RUN }} }'
